<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\CodeLanguage;
use App\Models\Item;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Database\Seeder;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {

        User::factory()->create([
            'name'     => 'Creator',
            'email'    => 'admin@admin.com',
            'password' => bcrypt('password'),
        ]);

        Category::create([
            "title"       => [
                "ka" => 'ამოხსნები',
                "en" => 'solutions'
            ],
            "slug"        => str()->slug('solutions'),
            "description" => [
                "ka" => "solutions category description",
                "en" => "solutions category description"
            ],
            "status"      => true
        ]);
        Tag::factory(20)->create();

        Item::factory()
            ->count(500)
            ->create()
            ->each(function ($item) {
                $randomTags = Tag::all()->random(3);

                // Attach the random tags to the item
                $item->tags()->attach($randomTags);
            });

        $languages = [
            '1C',
            '4D',
            'ABAP',
            'ABNF',
            'Access logs',
            'Ada',
            'Apex',
            'Arduino',
            'ARM assembler',
            'AVR assembler',
            'ActionScript',
            'Alan IF',
            'Alan',
            'AngelScript',
            'Apache',
            'AppleScript',
            'Arcade',
            'AsciiDoc',
            'AspectJ',
            'AutoHotkey',
            'AutoIt',
            'Awk',
            'Ballerina',
            'Bash',
            'Basic',
            'BBCode',
            'Blade',
            'BNF',
            'BQN',
            'Brainfuck',
            'C#',
            'C',
            'C++',
            'C/AL',
            'C3',
            'Cache Object Script',
            'Candid',
            'CMake',
            'COBOL',
            'CODEOWNERS',
            'Coq',
            'CSP',
            'CSS',
            "Cap'n Proto",
            'Chaos',
            'Chapel',
            'Cisco CLI',
            'Clojure',
            'CoffeeScript',
            'CpcdosC+',
            'Crmsh',
            'Crystal',
            'cURL',
            'Cypher',
            'D',
            'Dafny',
            'Dart',
            'Delphi',
            'Diff',
            'Django',
            'DNS Zone file',
            'Dockerfile',
            'DOS',
            'dsconfig',
            'DTS',
            'Dust',
            'Dylan',
            'EBNF',
            'Elixir',
            'Elm',
            'Erlang',
            'Excel',
            'Extempore',
            'F#',
            'FIX',
            'Flix',
            'Fortran',
            'FunC',
            'G-Code',
            'Gams',
            'GAUSS',
            'GDScript',
            'Gherkin',
            'Glimmer and EmberJS',
            'GN for Ninja',
            'Go',
            'Grammatical Framework',
            'Golo',
            'Gradle',
            'GraphQL',
            'Groovy',
            'GSQL',
            'HTML, XML',
            'HTTP',
            'Haml',
            'Handlebars',
            'Haskell',
            'Haxe',
            'High-level shader language',
            'Hy',
            'Ini, TOML',
            'Inform7',
            'IRPF90',
            'Iptables',
            'JSON',
            'JSONata',
            'Java',
            'JavaScript',
            'Jolie',
            'Julia',
            'Julia REPL',
            'Kotlin',
            'Lang',
            'LaTeX',
            'Leaf',
            'Lean',
            'Lasso',
            'Less',
            'LDIF',
            'Liquid',
            'Lisp',
            'LiveCode Server',
            'LiveScript',
            'LookML',
            'Lua',
            'Luau',
            'Macaulay2',
            'Makefile',
            'Markdown',
            'Mathematica',
            'Matlab',
            'Maxima',
            'Maya Embedded Language',
            'Mercury',
            'MetaPost',
            'MIPS Assembler',
            'Mint',
            'Mirth',
            'mIRC Scripting Language',
            'Mizar',
            'MKB',
            'MLIR',
            'Mojolicious',
            'Monkey',
            'Moonscript',
            'Motoko',
            'N1QL',
            'NSIS',
            'Never',
            'Nginx',
            'Nim',
            'Nix',
            'Oak',
            'Object Constraint Language',
            'OCaml',
            'Objective C',
            'Odin',
            'OpenGL Shading Language',
            'OpenSCAD',
            'Oracle Rules Language',
            'Oxygene',
            'PF',
            'PHP',
            'Papyrus',
            'Parser3',
            'Perl',
            'Phix',
            'Pine Script',
            'Plaintext',
            'Pony',
            'PostgreSQL & PL/pgSQL',
            'PowerOn',
            'PowerShell',
            'Processing',
            'Prolog',
            'Properties',
            'Protocol Buffers',
            'Puppet',
            'Python',
            'Python profiler results',
            'Python REPL',
            'Q#',
            'Q',
            'QML',
            'R',
            'Raku',
            'RakuDoc',
            'RakuQuoting',
            'RakuRegexe',
            'Razor CSHTML',
            'ReasonML',
            'Rebol & Red',
            'RenderMan RIB',
            'RenderMan RSL',
            'ReScript',
            'RiScript',
            'RISC-V Assembly',
            'Roboconf',
            'Robot Framework',
            'RPM spec files',
            'Ruby',
            'Rust',
            'RVT Script',
            'SAS',
            'SCSS',
            'SQL',
            'STEP Part 21',
            'Scala',
            'Scheme',
            'Scilab',
            'SFZ',
            'Shape Expressions',
            'Shell',
            'Smali',
            'Smalltalk',
            'SML',
            'Solidity',
            'Splunk SPL',
            'Stan',
            'Stata',
            'Structured Text',
            'Stylus',
            'SubUnit',
            'Supercollider',
            'Svelte',
            'Swift',
            'Tcl',
            'Terraform',
            'Test Anything Protocol',
            'Thrift',
            'Toit',
            'TP',
            'Transact-SQL',
            'TTCN-3',
            'Twig',
            'TypeScript',
            'Unicorn Rails log',
            'Unison',
            'VB.Net',
            'VBA',
            'VBScript',
            'VHDL',
            'Vala',
            'Verilog',
            'Vim Script',
            'WGSL',
            'X#',
            'X++',
            'x86 Assembly',
            'x86 Assembly (AT&T)',
            'XL',
            'XQuery',
            'YAML',
            'ZenScript',
            'Zephir',
            'Zig'
        ];

        foreach ($languages as $language) {
            CodeLanguage::create([
                'name' => $language,
                'code' => $language,
            ]);
        }
    }
}
